### ISSUE TITLE
MarkdownLivePreviewSyntax.sublime-settings::"word_wrap": true not functioning

### ISSUE THREAD

**Issue by william-voyek** [math2001/MarkdownLivePreview#34] opened 2017-08-19 04:52 UTC
I have added the `"word_wrap":true` setting to my syntax specific settings file but the preview is still not wrapping:

<img width="1072" alt="screenshot 2017-08-18 21 49 22" src="https://user-images.githubusercontent.com/989760/29483630-35511ba0-845f-11e7-9596-ee00fe8abe1d.png">

My settings file:
```
// These settings override both User and Default settings for the MarkdownLivePreviewSyntax syntax
{
    "show_tabs": true,
    "word_wrap": true
}
```

**Comment by wangray** [comment] 2017-08-26 20:20
I have the same issue.

**Comment by bkarlson** [comment] 2017-09-29 08:31
same, preview window not wrapping, a bit frustrating

**Comment by math2001** [comment] 2017-09-29 09:14
Hum... Looked into it and it's a bit weird. Word wrap **is on**, it's just not wrapping properly.

Can you please do the following:

1. Open a preview window
2. click on the tab of the *preview* (if you press <kbd>ctrl+p</kbd>, it should open on the preview's pane)
3. Go into the `View` menu, and see if the `Word Wrap` option is enabled.

In my case, it is, but wrapping the Phantom (the preview thing) doesn't seem to take into account the minimap, and to wrap properly at all.

**Comment by bkarlson** [comment] 2017-09-29 09:22
partial fix via custom css:
```
body {
    font-family: Verdana, "Open Sans", sans-serif;
    font-size: 13px;
    width:550px; /* adjust to your liking */
}

```

**Comment by bkarlson** [comment] 2017-09-29 09:26
Sorry, @math2001 , just noticed your prompt response. Yes, word wrap is enabled for both windows, still no avail:
![image](https://user-images.githubusercontent.com/30080507/31009801-ddbf5844-a532-11e7-81aa-bbbce260f69d.png)

**Comment by math2001** [comment] 2017-09-30 09:30
So, I guess that's Sublime's problem, with the `Phantom`. I'll look into it a bit more (I feel like images and `pre` tags might cause those bugs...)

**Comment by bkarlson** [comment] 2017-10-01 08:39
Yes, you're right, it's overly wide images & unbroken lines within `tt` or `code` elements that cause whole document to become too wide. 
Easy fix for `img` via custom css:
```css
img {width:680px}
```
(distorts images, but still)
Yet no fix for code blocks, minihtml is way too limited in my view. See if you can come up with a better idea

**Comment by math2001** [comment] 2017-10-01 08:52
Does it work? `width` isn't mentionned in the [minihtml](https://www.sublimetext.com/docs/3/minihtml.html) reference...

Did you try `witdth: 100%` and/or `max-width: 100%`?

**Comment by bkarlson** [comment] 2017-10-01 18:36
Yep, tried 100%, seems like it interpreted as 100px 😬 
See my current CSS below, at least it contains overall doc width within my panel width, but long lines in`<tt>` still remain unbroken and hang like hell, see below. Images are distorted, as `height:auto` is ignored, but at least I can see them w/o scrolling when width is fixed.

```css

body {
    font-family: Verdana, "Open Sans", sans-serif;
    font-size: 13px;
   background-color:white;
   width: 680px;
}

html {
   background-color:white;
    --light-bg: color(var(--background) blend(#eee 85%));
    --very-light-bg: color(var(--background) blend(#eee 92%));
}

img {width:680px}
```
![image](https://user-images.githubusercontent.com/30080507/31057759-0a6b66b8-a712-11e7-8527-3e71237f8c05.png)
![image](https://user-images.githubusercontent.com/30080507/31057760-0a6d80a6-a712-11e7-9828-22c961f8fac4.png)

**Comment by mrpinghe** [comment] 2017-12-06 22:13
Seeing the same bug. A bit more tweaking shows that if you put the full URL in the text, it messes up the wrapping. So if you use markdown to shorten that URL when preview, i.e. [link text](your full URL) in markdown, the preview would be all wrapping correctly

Hope that is helping somebody

**Comment by ixjx** [comment] 2018-06-04 05:45
+1 ,the same issue.
It seems the bug does not fixed up to now :(

**Comment by xiebruce** [comment] 2019-03-06 19:02
+1, seems not fix yet?

**Comment by OmarAlamoudi** [comment] 2019-07-02 22:36
+1. No fix yet?

**Comment by rafaelbeckel** [comment] 2019-08-10 23:38
+1

**Comment by math2001** [comment] 2019-11-16 01:01
I think I understand what the problem is: the image is too large, so it grows the preview. Otherwise, wrapping works.

So, this will be fixed with #48, so I'm closing this. (Feel free to re-open if you disagree)

**Closed by math2001** 2019-11-16 01:01 UTC
Labels: sublime-bug

**Comment by Ganthark** [comment] 2020-01-30 12:58
I still have this issue, is the fix released in the version available on package control?

**Comment by Anesthesius** [comment] 2021-01-26 17:41
> I still have this issue, is the fix released in the version available on package control?

I also have this issue when code blocks extend beyond the margins of the preview. If I manually add enough line-breaks to the code block so it doesn't extend beyond the margins of the preview, wrap works correctly again.
