### ISSUE TITLE
Image preview

### ISSUE THREAD

**Issue by ihodev** [math2001/MarkdownLivePreview#3] opened 2016-12-26 12:56 UTC
Is it possible to add image preview or sublime has some limitations in this area?

**Comment by math2001** [comment] 2016-12-28 00:24
For sure, there's something to fix. 

- if you load the image from your computer, they need to be prefixed with `file://` and with the absolute path. (this is MarkdownLivePreview's job)
- I couldn't get sublime text to show an image loaded from internet: MarkdownLivePreview needs to convert it base64 (and cache it), then it works, although ST kinda freeze (depending of the size of the image of course, and your computer's perfs).
- With some images, I only get the top to show up, and bottom's not rendered. So, I'll do some tests, because this is really weird.

And, this made me think about a major improvement: **separate each paragraph (one phantom for each), and update only the one that has been updated**. Like this, it wouldn't reload the image(s) and the other paragraphs each time. 

So, yep, here's a few things to improve... 😄

**Comment by math2001** [comment] 2016-12-28 01:24
I understand why the bottom wasn't showing up: the popup wasn't big enough. It like if the image was in `position: absolute`... You have to add text to make the popup bigger, but the text is hidden (by the image).

**Comment by yangweijie** [comment] 2017-01-01 04:23
here is  a example shows how A img size affected by paragraph

![image](https://cloud.githubusercontent.com/assets/1614114/21580144/4e9efcde-d01a-11e6-87ac-17c40a7ee74b.png)


And  if i use show_popup api, it simply give right size of pic

![image](https://cloud.githubusercontent.com/assets/1614114/21580149/07d70bba-d01b-11e6-9c09-94aeb20ca10f.png)

if i  use param to limit popup window which size is smaller than the pic's size(50x50 < 200x150)

the popup view  display two scroll bar

![image](https://cloud.githubusercontent.com/assets/1614114/21580163/1759b618-d01c-11e6-8577-77c2694e8bab.png)


maybe the author can tell us  the difference between `show_popup` AND `add_phantom`.

or just as you thought , each p use a  phantom. That is worset. Because  we think one should be enough.

It is just a beatifyed Html.

**Comment by math2001** [comment] 2017-01-01 06:31
With the phantoms, you get more control over the size... it sound bad right now, but it's the truth. I don't know how to set the width of the popup to be 100% of the available space. It's a problem when there is not enough text, it looks... weird to me. The other difference that I'm aware of is that you can have only 1 popup, instead a several when you use the phantoms.

So, here (are or is. Are sounds weird) the choices:

- use popup: we can use the images, scrollbar, and automatically adapt to the size of the image. The problem is that when there is not enough text, it doesn't use the full width, which looks a bit weird...
- use phantoms: completely fucks up when it comes to images, no scrollbar, no adaptation.
- or we change depending on the content: if there is an image, use the popup, otherwise, use the phantoms. I think this is the best solution, although it might shock when you're not aware (if you insert a really small image, and you don't have enough text to oblige the popup to take up the entire width).

Just an aside note: there need to be at least 1 char to be able to render a popup (so a space works).

> or just as you thought , each p use a phantom. That is worset. Because we think one should be enough.

I don't understand this... Do you think it'd be good to do several phantom, or stick with one? BTW, what does the `worset` means?

Thanks for your time, both of you! 👍  😄

**Comment by yangweijie** [comment] 2017-01-01 07:22
After my research, i find out how the picture  display right size. 
![example](https://cloud.githubusercontent.com/assets/1614114/21580477/899a741c-d033-11e6-833a-663bcd80e1f5.png)

Your reply reminds me a plugin i red  a few months.

[ Latex Equation Preview](http://www.tuicool.com/articles/NVrUVr). So i got up to read the source code of that plugin.

```
if content_region:
        file_converter = FileConverter(dir_name)
        log("temp_dir is {}".format(dir_name))
        tex_file = file_converter.create_temptex(
            view.substr(content_region), file_name)
        png_file = file_converter.tex_to_png(tex_file, FLAG)
        log("png file is {}".format(png_file))
        png_str = file_converter.png_to_datastr(png_file)
        html_str = """
        <style>
        .block {{
            background-color:{};
            position:relative;
            display: inline;
        }}
        </style>
        <span class="block">
        <a href="#"><img src="data:image/png;base64,{}" /></a>
        </span>
        """.format(plugin_settings.get("equation_background_color"), png_str)
        group_name = PHANTOM_GROUP + str(content_region.b + 1)
        log('group_name is {}'.format(group_name))
        return {"region":
                sublime.Region(content_region.b, content_region.b + 1)
                if plugin_settings.get("equation_inline_position") == "right"
                else sublime.Region(content_region.a, content_region.a),
                "content": html_str,
                "layout": sublime.LAYOUT_BLOCK
                if FLAG == BLOCK_FLAG else sublime.LAYOUT_INLINE,
                "on_navigate": lambda href: view.erase_phantoms(group_name)}
```
![image](https://cloud.githubusercontent.com/assets/1614114/21580480/f8213a4c-d033-11e6-834d-e6c0e686bcfe.png)

![image](https://cloud.githubusercontent.com/assets/1614114/21580482/0d7d707c-d034-11e6-87c7-593248794416.png)

Then i wrote some html code in left view. It works!!!.

No `width` and `height `attributes.

It’s certain works Http or Https img resouce. It‘s plaint base64 encoded Data.

And, i think  u can realize the szie of img format witch works on other platform. Such as Kancloud.cn

![image](https://cloud.githubusercontent.com/assets/1614114/21580489/d3aeda56-d034-11e6-9900-149ce1e5a9f8.png)

Another advice,  auto swith of preview view.  Which means i opend a md file, alt+m  click mouse to switch other tabs those are not md file. The preview phantom rended still open and is not relate the tab i focus on.

![image](https://cloud.githubusercontent.com/assets/1614114/21580492/4cad2296-d035-11e6-86bb-871b271ccff3.png)

And i have to close it manually. 

![image](https://cloud.githubusercontent.com/assets/1614114/21580494/789455aa-d035-11e6-8777-163280e28ae4.png)

And i switch to another md file it doens't auto switch to it. So  u deside how  to response. alt+m means to preivew all md file or just current one、when previewed file is not focusing, shoud plugin close it.

PS: Seen pic above u may see I'm a Chinese. Sorry for my poor english . Hope u can understand my view.

**Comment by yangweijie** [comment] 2017-01-01 07:27
Maybe  a popup api used to  VIew pic clearly a great idea. We can get local file size. Attach two links to room up or room in.

**Comment by math2001** [comment] 2017-01-01 08:11
After few tests:

```python
def to_base64(path):
    with open(path, 'rb') as fp:
        content = fp.read()
    return base64.standard_b64encode(content)
```

**Comment by math2001** [comment] 2017-01-01 09:59
Ok, local images look like they're working. Now, the funny part's coming: loading and caching from the web.

**Comment by math2001** [comment] 2017-01-22 08:45
Ok, it's been a big while now since the image loading is working. There's still some [things to improve](https://github.com/math2001/MarkdownLivePreview/blob/master/MarkdownLivePreview.tasks#L5-L6), but it's working.

**Closed by math2001** 2017-01-22 08:45 UTC
