### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by ooing** [math2001/MarkdownLivePreview#7] opened 2017-01-09 01:58 UTC
hi ,thanks you develop this plugin!
I  hava some  suggestions

*  sublime auto preview when open markdow of file. not need press  alt+m
*   code and preview should synchronized scrolling

I am sorry for bad english

**Comment by math2001** [comment] 2017-01-09 02:25
Hello!

Thanks for your feedback!

> sublime auto preview when open markdown of file. not need press alt+m

Starting working on this right now.

> code and preview should synchronized scrolling

There's a part that I disabled that was doing this. The problem is when images comes into the game... it's already on my todo list, but I'll look a bit more at this.

**Comment by math2001** [comment] 2017-01-09 04:04
Ok, I'm nearly done with the first one. There's a little pb though: as soon as a markdown file is opened, it's showed up. Even when you just open it from the sidebar (just one click, so it's in `transient` mode). Luckily, you can preview it from the `Goto Anything` (hover it's name, it's showed in the background) without having it to popup.

So, I'll push the changes in a sec

**Comment by ooing** [comment] 2017-01-09 05:57
@math2001   thanks

**Comment by ooing** [comment] 2017-01-09 06:38
@math2001  hi
I set  "markdown_live_preview_on_open": true   on "\User\Preferences.sublime-settings"
and restart but when I open markdown file , it not show up,  my config is next
`{
	"bold_folder_labels": true,
	"color_scheme": "Packages/User/SublimeLinter/Monokai (SL).tmTheme",
	"ensure_newline_at_eof_on_save": true,
	"folder_exclude_patterns":
	[
		".idea",
		".git"
	],
	"font_size": 20,
	"highlight_line": true,
	"highlight_modified_tabs": true,
	"ignored_packages":
	[
		"Vintage"
	],
	"markdown_live_preview_on_open": true,
	"preview_on_click": false,
	"show_encoding": true,
	"show_tab_close_buttons": false,
	"theme": "SoDaReloaded Light.sublime-theme",
	"trim_trailing_white_space_on_save": true,
	"update_check": false,
	"markdown_live_preview_on_open": true
}`

**Comment by math2001** [comment] 2017-01-09 06:41
It's in the wrong setting file. I'm currently updating the README to explain this. You need to add this in the `MarkdownLivePreview` settings, not your global ones. To do so, search up in the command palette:

`Preferences: MarkdownLivePreview Settings`

Hit enter, and it's in this *left* file that you have to add 

```json
"markdown_live_preview_on_open": true
```

**Comment by ooing** [comment] 2017-01-09 07:01
@math2001  thanks it's successs 
it can show current window (cuernt  edit  area ) ? not  open a new window.

**Comment by math2001** [comment] 2017-01-09 07:06
> @math2001 thanks it's successs

Cool!

> it can show current window (cuernt edit area ) ? not open a new window.

Do you want it to show only in the current window and to not open a new one? That's how it was working before but it made ST crash. So I'm currently working on it, but I've released this stable multi-windows version while I haven't find a stable mono-window solution...

I'm going to close this issue, but can you raise a new one for `code and preview should synchronised scrolling`? I prefer when there is one issue *per* request.

**Closed by math2001** 2017-01-09 07:06 UTC
Labels: enhancement

**Comment by ooing** [comment] 2017-01-09 07:10
ok, thanks
