### ISSUE TITLE
Ver. 3.0.0 not working

### ISSUE THREAD

**Issue by cilia** [math2001/MarkdownLivePreview#95] opened 2019-11-21 23:02 UTC
Installed ver. 3.0.0, invoked preview using the command palette and it shows a blank preview pane next to the source md file. Any idea why?

**Comment by h888866j** [comment] 2019-11-21 23:26
Mine is not working as well!
After installation, there are no place to changes settings(not displaying in the Preference--Package Setting), alt+m not working as well.
>or search up in the command
>  palette: 'MarkdownLivePreview: Toggle'. Hit enter and you're done.
searching in the command, nothing come up ~~!

**Comment by math2001** [comment] 2019-11-26 21:57
> alt+m not working as well.

See #96 

> it shows a blank preview pane next to the source md file

Can you have a look in console and see if there is an error there? Does it happen for every file?

**Comment by cilia** [comment] 2019-11-28 22:37
Somehow it's now showing the output. I don't think I've changed anything for MarkdownLivePreview but it's working now. The only thing shown in the console is 

> using gpu buffer for window

Btw, in #96 you mentioned there was a new release two days ago but I don't see it on PackageControl, maybe you didn't tag it?

**Comment by math2001** [comment] 2019-11-29 05:55
> Somehow it's now showing the output

Maybe it just needed a restart... Are you previewing the same file?

> you mentioned there was a new release two days ago but I don't see it on PackageControl, maybe you didn't tag it?

I was referencing `v3.0.0` there. Nonetheless, there were a few bug fixes committed by not tagged, so thanks for reminding me. `v3.0.1` is pushed :slightly_smiling_face: 

I'm closing this because it isn't reproducible anymore, reopen an other issue if you encounter a bug again (and don't forget to have a look at the console :wink: )

**Closed by math2001** 2019-11-29 05:55 UTC
